name: SSH into our runners

on:
  push:
    branches:
      - ping_author

jobs:
  ssh_runner:
    name: "SSH"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Process report
        shell: bash
        run: |
          {
            echo 'REPORT_TEXT<<EOF'
            python3 utils/process.py
            echo EOF
          } >> "$GITHUB_ENV"

      - name: Send processed report
        uses: slackapi/slack-github-action@6c661ce58804a1a20f6dc5fbee7f0381b469e001
        with:
          # Slack channel id, channel name, or user id to post message.
          # See also: https://api.slack.com/methods/chat.postMessage#channels
          channel-id: '#transformers-ci-feedback-tests'
          # For posting a rich message using Block Kit
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "${{ env.REPORT_TEXT }}"
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_CIFEEDBACK_BOT_TOKEN }}
